name = "burn-after-reading"
main = "src/index.js"
compatibility_date = "2024-04-05"

# KV Namespace binding
# Run `npx wrangler kv namespace create SECRETS_KV` to get the ID
[[kv_namespaces]]
binding = "SECRETS_KV"
id = "97a12cb829af4e70b1ec28af9d382ab9" 
preview_id = "YOUR_KV_NAMESPACE_PREVIEW_ID" # Optional, for `wrangler dev`

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "burn-after-reading-files"


